# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/lilin/repos/NotesForGraphics/task8works/task8/CGL/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/lilin/repos/NotesForGraphics/task8works/task8/CGL/deps/glew/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/lilin/repos/NotesForGraphics/task8works/task8/CGL/deps/glfw/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/lilin/repos/NotesForGraphics/task8works/task8/CGL/deps/glfw/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/lilin/repos/NotesForGraphics/task8works/task8/CGL/deps/glfw/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/lilin/repos/NotesForGraphics/task8works/task8/CGL/deps/glfw/src/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/lilin/repos/NotesForGraphics/task8works/task8/CGL/deps/glfw/src/glfw3Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/lilin/repos/NotesForGraphics/task8works/task8/CGL/deps/glfw/src/glfw_config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/lilin/repos/NotesForGraphics/task8works/task8/CGL/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/FindFreetype.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/FindOpenGL.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/FindPkgConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/lilin/repos/NotesForGraphics/task8works/task8/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.17.1/bin/cmake -H/Users/lilin/repos/NotesForGraphics/task8works/task8 -B/Users/lilin/repos/NotesForGraphics/task8works/task8
